### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by synovtan** [sugarcrm/Support-Helpers-Packager#4]
I had an issue with installation where upon launching the command 

`composer install --no-dev`

I get the following error:

`  
[Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - name : Does not match the regex pattern ^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$  
`

A change in the composer.json line 2 from 

`"name": "sugarcrm/Sugar-Instance-Packager",`

to 

`"name": "sugarcrm/sugar-instance-packager",`

fixed the install issue.

Best regards,
Vlad

**Comment by jwigg-sugar** [comment]
Thanks Vlad, this should be fixed now!
